---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-tf-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-tf
  template:
    metadata:
      labels:
        app: hello-tf
    spec:
      containers:
      - name: hello-kubernetes-tf
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "80m"
          limits:
            memory: "128Mi"
            cpu: "250m"
